#!/usr/bin/bash
cmsenv
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_0J_PTH_10_200_Config.py  --OutputFileName "$1"_ggH_STXS_2.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_GE2J_MJJ_0_350_PTH_60_120_Config.py  --OutputFileName "$1"_ggH_STXS_8.root"
tmux select-layout even-vertical
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_1J_PTH_0_60_Config.py  --OutputFileName "$1"_ggH_STXS_3.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_GE2J_MJJ_350_700_PTHJJ_0_25_Config.py  --OutputFileName "$1"_ggH_STXS_9.root"
tmux select-layout even-vertical
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_1J_PTH_120_200_Config.py  --OutputFileName "$1"_ggH_STXS_4.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_GE2J_MJJ_350_700_PTHJJ_GE25_Config.py  --OutputFileName "$1"_ggH_STXS_10.root"
tmux select-layout even-vertical
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_1J_PTH_60_120_Config.py  --OutputFileName "$1"_ggH_STXS_5.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_GE2J_MJJ_GE700_PTHJJ_0_25_Config.py  --OutputFileName "$1"_ggH_STXS_11.root"
tmux select-layout even-vertical
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_GE2J_MJJ_0_350_PTH_0_60_Config.py  --OutputFileName "$1"_ggH_STXS_6.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_GE2J_MJJ_GE700_PTHJJ_GE25_Config.py  --OutputFileName "$1"_ggH_STXS_12.root"
tmux select-layout even-vertical
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_GE2J_MJJ_0_350_PTH_120_200_Config.py  --OutputFileName "$1"_ggH_STXS_7.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_GE200_Config.py --OutputFileName "$1"_ggH_STXS_13.root"

python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/ggH_STXS/ggH_PTH_0_200_0J_PTH_0_10_Config.py  --OutputFileName $1_ggH_STXS_1.root
