#!/usr/bin/bash
cmsenv
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_0J_Config.py  --OutputFileName "$1"_VBF_STXS_1.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_1J_Config.py  --OutputFileName "$1"_VBF_STXS_2.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_GE2J_MJJ_0_60_Config.py  --OutputFileName "$1"_VBF_STXS_3.root"
tmux select-layout even-vertical
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_GE2J_MJJ_120_350_Config.py  --OutputFileName "$1"_VBF_STXS_4.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_GE2J_MJJ_60_120_Config.py  --OutputFileName "$1"_VBF_STXS_5.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_GE2J_MJJ_GE350_PTH_0_200_MJJ_350_700_PTHJJ_0_25_Config.py  --OutputFileName "$1"_VBF_STXS_6.root"
tmux select-layout even-vertical
tmux split-window "eval \`scramv1 runtime -sh\` && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_GE2J_MJJ_GE350_PTH_0_200_MJJ_350_700_PTHJJ_GE25_Config.py  --OutputFileName "$1"_VBF_STXS_7.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_GE2J_MJJ_GE350_PTH_0_200_MJJ_GE700_PTHJJ_0_25_Config.py  --OutputFileName "$1"_VBF_STXS_8.root && python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/"$1"/VBF_STXS/VBF_GE2J_MJJ_GE350_PTH_0_200_MJJ_GE700_PTHJJ_GE25_Config.py  --OutputFileName "$1"_VBF_STXS_9.root"
tmux select-layout even-vertical
python CreateDatacard.py --AnalysisConfigFiles AnalysisCategories/UserAnalysisCategories/*_Config.py --SampleConfigFiles Samples/UserSamples/$1/VBF_STXS/VBF_GE2J_MJJ_GE350_PTH_GE200_Config.py  --OutputFileName $1_VBF_STXS_10.root
